import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/ui";
import { Footer } from "@/components/ui/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/img/icon_title.ico" />
      <body>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
